### ISSUE TITLE
OAuth 2.0 support?  I appologize if this was covered previously.  Google is confusing us with misleading "wrong password" response.

### ISSUE THREAD

**Issue by crawkn** [jankeirse/tvhgooglemapi#40] opened 2015-06-24 10:40 UTC

**Comment by jankeirse** [comment] 2015-07-22 13:19
Duplicate of https://github.com/jankeirse/tvhgooglemapi/issues/33

**Closed by jankeirse** 2015-07-22 13:19 UTC
Labels: duplicate

**Comment by crawkn** [comment] 2015-07-23 14:44
Thanks but I am not too sure I know how to interpret #33
<https://github.com/jankeirse/tvhgooglemapi/issues/33>.  My best guess is
that the OAuth 2.0 support would be included in whatever is meant by
"migrating" to Gmail API (adding compatibility?).  And by "acknowledged,"
do you mean that the migration is likely to occur, or is it a non-committal
response, along the lines of "yes, it would have the effect you suggest if
I had time to do it, which I may or may not"?

Is there any way I can be informed if the compatibility is added, so that I
may upgrade?

Thanks very much for the useful tool, and I am a big fan of yours
regardless if you ever find the time to perfect it!


*Ken Crawford*

**Comment by jankeirse** [comment] 2015-07-23 15:04
Hey Ken, 

I acknowledge an issue if I understand what the problem is and agree that it can indeed be considered a problem (as apposed to ie a feature someone may not like or something beyond the scope of the tool.) 
It is indeed a non-committal response, along the lines of "yes, it would have the effect you suggest if I had time to do it, which I may or may not"?
If you want to be informed of implementation of oauth2 (and a bit more with it) you can subscribe to  issue #33 . 
The current implementation uses the imap/smtp protocols without oauth, an implementation with the gmail api would use https with oauth 2.0. 

As for the likeliness of this being implemented, I'll be honest: as long as it can be configured to work as it does today I'm extremely unlikely to be able to prioritize a new implementation myself. 
Contributions are welcomed though. 

Thanks for your feedback and sorry I can't help you any better at this time,

Jan

**Comment by crawkn** [comment] 2015-07-23 17:54
No worries, like I say your hard work is appreciated with or without this
upgrade.  I have just today established a folder for developers to whom I
would like to contribute when I have an income, at present I am unable, but
you are worthy of a little effort to remember to support when I can.

Please be kind enough to provide me a direct link to your contributions
acceptance tool or whatever.  Sounds like a good link to add to your
signature block for your convenience and personal enrichment!

Already watching, so I will look for an upgrade if it comes.


*Ken Crawford*
